[versions]
quarkus = "3.29.3"
quarkus-mybatis = "2.4.2"
rest-assured = "5.5.6"
spotless = "8.1.0"

[libraries]
quarkus-arc = { group = "io.quarkus", name = "quarkus-arc", version.ref = "quarkus" }
quarkus-rest = { group = "io.quarkus", name = "quarkus-rest", version.ref = "quarkus" }
quarkus-rest-jackson = { group = "io.quarkus", name = "quarkus-rest-jackson", version.ref = "quarkus" }
quarkus-config-yaml = { group = "io.quarkus", name = "quarkus-config-yaml", version.ref = "quarkus" }
quarkus-logging-json = { group = "io.quarkus", name = "quarkus-logging-json", version.ref = "quarkus" }
quarkus-hibernate-validator = { group = "io.quarkus", name = "quarkus-hibernate-validator", version.ref = "quarkus" }
quarkus-smallrye-openapi = { group = "io.quarkus", name = "quarkus-smallrye-openapi", version.ref = "quarkus" }
quarkus-smallrye-health = { group = "io.quarkus", name = "quarkus-smallrye-health", version.ref = "quarkus" }
quarkus-micrometer-registry-prometheus = { group = "io.quarkus", name = "quarkus-micrometer-registry-prometheus", version.ref = "quarkus" }
quarkus-jdbc-mysql = { group = "io.quarkus", name = "quarkus-jdbc-mysql", version.ref = "quarkus" }
quarkus-mybatis = { group = "io.quarkiverse.mybatis", name = "quarkus-mybatis", version.ref = "quarkus-mybatis" }

quarkus-junit5-mockito = { group = "io.quarkus", name = "quarkus-junit5-mockito", version.ref = "quarkus" }
rest-assured = { group = "io.rest-assured", name = "rest-assured", version.ref = "rest-assured" }

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
